name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Build client
        run: cd client && npm install && npm run build
      - name: Build server
        run: cd server && npm install && npm run build
      - name: Deploy with rsync
        run: rsync -rav --delete --exclude='node_modules' ./ root@116.203.15.40:/game
      - name: Restart game
        run: ssh root@116.203.15.40 "cd /game/server && chmod +x restart.sh && ./restart.sh"